language: node_js

services:
  - docker

sudo: required

node_js:
  - 12.16.1

cache: yarn

script:
  - cd ui
  - yarn

after_success:
    - echo ${TRAVIS_REPO_SLUG}
    - cd ..
    - .ci/comment-pr.sh
